FROM node:alpine as build
WORKDIR /app
COPY package.json .
RUN npm config set unsafe-perm true
RUN npm install
COPY . .
RUN chown -R node /app/node_modules
RUN npm run build

FROM nginx
COPY --from=build /app/build /usr/share/nginx/html