version: '3.8'

services:
  mysql_db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_DATABASE: stt_db
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_HOST: localhost

  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    ports:
      - "3050:80"

  backend:
    build: ./backend
    depends_on:
      - mysql_db
    environment:
      MYSQL_DATABASE: stt_db
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
      MYSQL_HOST_IP: mysql_db

  frontend:
    stdin_open: true
    tty: true

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8000:8080
    depends_on:
      - mysql_db
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db
    