version: "3.8"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - /app/node_modules
